version: '3.8'

services:
  app:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
    command: pnpm run start