name: LATAMSHOP CI/CD - Dev

on:
  # 1. Corre cuando se abre o actualiza un PR hacia 'dev'
  pull_request:
    branches: ["dev"]

  # 2. Corre cuando el código finalmente entra a 'dev' (vía Merge)
  push:
    branches: ["dev"]

jobs:
  validation:
    runs-on: ubuntu-latest
    # Usamos una imagen ligera de Alpine para optimizar recursos
    container:
      image: node:20-alpine

    steps:
      - name: Install Git
        run: apk add --no-cache git

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint and Type-check
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test
